#!/usr/bin/env python3
"""
Axsupport — LLM Gateway
Multi-provider LLM client with automatic fallback.
Auto-generated by Agent Factory.
"""
import os
import json
import logging
from typing import Optional, Dict, List

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("llm_gateway")

PROVIDERS = {
    "anthropic": {
        "name": "Anthropic Claude",
        "env_var": "ANTHROPIC_API_KEY",
    },
    "openai": {
        "name": "OpenAI",
        "env_var": "OPENAI_API_KEY",
    },
    "openrouter": {
        "name": "OpenRouter",
        "env_var": "OPENROUTER_API_KEY",
    },
}


def _env(key: str, default=None):
    """Get environment variable."""
    return os.environ.get(key, default)


def call_with_fallback(
    prompt: str,
    providers: List[str] = None,
    system: str = None,
    max_tokens: int = 4096,
    temperature: float = 0.7,
    json_output: bool = False,
) -> Dict:
    """
    Call LLM with automatic fallback across providers.

    Returns:
        {
            "ok": True/False,
            "text": "response text",
            "provider": "provider_name",
            "model": "model_name",
            "error": None or error message
        }
    """
    providers = providers or ['anthropic', 'openai', 'openrouter']

    for provider in providers:
        try:
            result = _call_provider(provider, prompt, system, max_tokens, temperature, json_output)
            if result.get("ok"):
                return result
        except Exception as e:
            log.warning(f"{provider} failed: {e}")
            continue

    return {"ok": False, "error": "All providers failed", "text": ""}


def _call_provider(
    provider: str,
    prompt: str,
    system: str,
    max_tokens: int,
    temperature: float,
    json_output: bool,
) -> Dict:
    """Call a specific provider."""

    if provider not in PROVIDERS:
        raise ValueError(f"Unknown provider: {provider}")

    config = PROVIDERS[provider]

    
    if provider == "anthropic":
        return _call_anthropic(prompt, system, max_tokens, temperature, json_output)
    

    
    if provider == "openai":
        return _call_openai(prompt, system, max_tokens, temperature, json_output)
    

    

    

    raise NotImplementedError(f"Provider {provider} not implemented")



def _call_anthropic(prompt: str, system: str, max_tokens: int, temperature: float, json_output: bool) -> Dict:
    """Call Anthropic Claude API."""
    try:
        import anthropic
        api_key = _env("ANTHROPIC_API_KEY")
        if not api_key:
            raise ValueError("ANTHROPIC_API_KEY not set")

        client = anthropic.Anthropic(api_key=api_key)

        messages = [{"role": "user", "content": prompt}]

        response = client.messages.create(
            model="claude-sonnet-4-7",
            max_tokens=max_tokens,
            temperature=temperature,
            system=system or "You are a helpful AI assistant.",
            messages=messages,
        )

        text = response.content[0].text

        return {
            "ok": True,
            "text": text,
            "provider": "anthropic",
            "model": response.model,
            "error": None,
        }
    except Exception as e:
        return {"ok": False, "error": str(e), "provider": "anthropic"}




def _call_openai(prompt: str, system: str, max_tokens: int, temperature: float, json_output: bool) -> Dict:
    """Call OpenAI API."""
    try:
        import openai
        api_key = _env("OPENAI_API_KEY")
        if not api_key:
            raise ValueError("OPENAI_API_KEY not set")

        client = openai.OpenAI(api_key=api_key)

        messages = [
            {"role": "system", "content": system or "You are a helpful AI assistant."},
            {"role": "user", "content": prompt}
        ]

        response = client.chat.completions.create(
            model="gpt-4o",
            messages=messages,
            max_tokens=max_tokens,
            temperature=temperature,
        )

        text = response.choices[0].message.content

        return {
            "ok": True,
            "text": text,
            "provider": "openai",
            "model": response.model,
            "error": None,
        }
    except Exception as e:
        return {"ok": False, "error": str(e), "provider": "openai"}






def status() -> Dict:
    """Get status of all configured providers."""
    providers_status = {}

    for provider_id, config in PROVIDERS.items():
        env_var = config.get("env_var")
        if env_var and env_var != "None":
            has_key = bool(_env(env_var))
            providers_status[provider_id] = {
                "name": config["name"],
                "configured": has_key,
            }
        else:
            # Local provider
            providers_status[provider_id] = {
                "name": config["name"],
                "configured": True,
            }

    return {
        "providers": providers_status,
        "default_order": ['anthropic', 'openai', 'openrouter'],
    }


if __name__ == "__main__":
    # Test
    result = call_with_fallback("Hello, how are you?")
    print(json.dumps(result, indent=2))