#!/usr/bin/env python3
"""
Warp - LLM Gateway
Multi-provider LLM client with automatic fallback.
Auto-generated by Agent Factory.
"""
import json
import logging
import os
import queue
import subprocess
import threading
import time
from typing import Dict, List, Optional

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("llm_gateway")

DEFAULT_PROVIDER_ORDER = ["anthropic", "openai", "openrouter", "codex_app_server"]

PROVIDERS = {
    "anthropic": {
        "name": "Anthropic Claude",
        "env_var": "ANTHROPIC_API_KEY",
    },
    "openai": {
        "name": "OpenAI",
        "env_var": "OPENAI_API_KEY",
        "model_env_var": "OPENAI_MODEL",
    },
    "openrouter": {
        "name": "OpenRouter",
        "env_var": "OPENROUTER_API_KEY",
        "model_env_var": "OPENROUTER_MODEL",
    },
    "codex_app_server": {
        "name": "Codex",
        "env_var": "CODEX_APP_SERVER_URL",
        "model_env_var": "CODEX_APP_SERVER_MODEL",
    },
}

PROVIDER_ALIASES = {
    "codex": "codex_app_server",
    "codex-app-server": "codex_app_server",
}


def _env(key: str, default=None):
    """Get environment variable."""
    return os.environ.get(key, default)


def _provider_id(provider: str) -> str:
    return PROVIDER_ALIASES.get(provider, provider)


def call_with_fallback(
    prompt: str,
    providers: List[str] = None,
    system: str = None,
    max_tokens: int = 16384,
    temperature: float = 0.7,
    json_output: bool = False,
    model: Optional[str] = None,
) -> Dict:
    """
    Call LLM with automatic fallback across providers.

    Returns:
        {
            "ok": True/False,
            "text": "response text",
            "provider": "provider_name",
            "model": "model_name",
            "error": None or error message
        }
    """
    providers = providers or DEFAULT_PROVIDER_ORDER
    failures = []

    for provider in providers:
        try:
            result = _call_provider(provider, prompt, system, max_tokens, temperature, json_output, model)
            if result.get("ok"):
                if failures:
                    result["warnings"] = failures
                return result
            failure = {
                "provider": result.get("provider") or _provider_id(provider),
                "error": result.get("error") or "Provider returned an unsuccessful response",
            }
            failures.append(failure)
            log.warning("%s failed: %s", failure["provider"], failure["error"])
        except Exception as e:
            failure = {"provider": _provider_id(provider), "error": str(e)}
            failures.append(failure)
            log.warning("%s failed: %s", failure["provider"], failure["error"])
            continue

    error_details = "; ".join(f"{item['provider']}: {item['error']}" for item in failures)
    return {"ok": False, "error": f"All providers failed: {error_details}" if error_details else "All providers failed", "text": "", "warnings": failures}


def _call_provider(
    provider: str,
    prompt: str,
    system: str,
    max_tokens: int,
    temperature: float,
    json_output: bool,
    model: Optional[str] = None,
) -> Dict:
    """Call a specific provider."""
    provider = _provider_id(provider)

    if provider not in PROVIDERS:
        raise ValueError(f"Unknown provider: {provider}")

    if provider == "anthropic":
        return _call_anthropic(prompt, system, max_tokens, temperature, json_output, model)

    if provider == "openai":
        return _call_openai(prompt, system, max_tokens, temperature, json_output, model)

    if provider == "openrouter":
        return _call_openrouter(prompt, system, max_tokens, temperature, json_output, model)

    if provider == "codex_app_server":
        return _call_codex_app_server(prompt, system, max_tokens, temperature, json_output, model)

    raise NotImplementedError(f"Provider {provider} not implemented")


def _response_text(response) -> str:
    return response.choices[0].message.content or ""


def _chat_completion(
    *,
    provider: str,
    api_key: str,
    base_url: Optional[str],
    model: str,
    prompt: str,
    system: str,
    max_tokens: int,
    temperature: float,
    json_output: bool,
    default_headers: Optional[Dict[str, str]] = None,
) -> Dict:
    import openai

    client_kwargs = {"api_key": api_key}
    if base_url:
        client_kwargs["base_url"] = base_url
    if default_headers:
        client_kwargs["default_headers"] = default_headers
    client = openai.OpenAI(**client_kwargs)

    messages = [
        {"role": "system", "content": system or "You are a helpful AI assistant."},
        {"role": "user", "content": prompt},
    ]
    request = {
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": temperature,
    }
    if json_output:
        request["response_format"] = {"type": "json_object"}

    response = client.chat.completions.create(**request)

    return {
        "ok": True,
        "text": _response_text(response),
        "provider": provider,
        "model": response.model,
        "error": None,
    }


def _call_anthropic(prompt: str, system: str, max_tokens: int, temperature: float, json_output: bool, model: Optional[str] = None) -> Dict:
    """Call Anthropic Claude API."""
    try:
        import anthropic

        api_key = _env("ANTHROPIC_API_KEY")
        if not api_key:
            raise ValueError("ANTHROPIC_API_KEY not set")

        client = anthropic.Anthropic(api_key=api_key)

        messages = [{"role": "user", "content": prompt}]

        response = client.messages.create(
            model=model or "claude-sonnet-4-7",
            max_tokens=max_tokens,
            temperature=temperature,
            system=system or "You are a helpful AI assistant.",
            messages=messages,
        )

        text = response.content[0].text

        return {
            "ok": True,
            "text": text,
            "provider": "anthropic",
            "model": response.model,
            "error": None,
        }
    except Exception as e:
        return {"ok": False, "error": str(e), "provider": "anthropic"}


def _call_openai(prompt: str, system: str, max_tokens: int, temperature: float, json_output: bool, model: Optional[str] = None) -> Dict:
    """Call OpenAI API."""
    try:
        api_key = _env("OPENAI_API_KEY")
        if not api_key:
            raise ValueError("OPENAI_API_KEY not set")

        return _chat_completion(
            provider="openai",
            api_key=api_key,
            base_url=None,
            model=model or _env("OPENAI_MODEL", "gpt-5.4-mini"),
            prompt=prompt,
            system=system,
            max_tokens=max_tokens,
            temperature=temperature,
            json_output=json_output,
        )
    except Exception as e:
        return {"ok": False, "error": str(e), "provider": "openai"}


def _call_openrouter(prompt: str, system: str, max_tokens: int, temperature: float, json_output: bool, model: Optional[str] = None) -> Dict:
    """Call OpenRouter through its OpenAI-compatible chat completions API."""
    try:
        api_key = _env("OPENROUTER_API_KEY")
        if not api_key:
            raise ValueError("OPENROUTER_API_KEY not set")

        headers = {"X-Title": _env("OPENROUTER_APP_TITLE", "Warp")}
        referer = _env("OPENROUTER_HTTP_REFERER")
        if referer:
            headers["HTTP-Referer"] = referer

        return _chat_completion(
            provider="openrouter",
            api_key=api_key,
            base_url="https://openrouter.ai/api/v1",
            model=model or _env("OPENROUTER_MODEL", "deepseek/deepseek-v4-flash"),
            prompt=prompt,
            system=system,
            max_tokens=max_tokens,
            temperature=temperature,
            json_output=json_output,
            default_headers=headers,
        )
    except Exception as e:
        return {"ok": False, "error": str(e), "provider": "openrouter"}


def _codex_app_server_input_text(prompt: str, system: str, json_output: bool) -> str:
    """Build a single text input for Codex app-server turn/start."""
    parts = []
    if system:
        parts.extend(["System instructions:", system.strip(), ""])
    parts.extend(["User request:", prompt.strip()])
    if json_output:
        parts.extend(["", "Return valid JSON only."])
    return "\n".join(parts)


def _codex_send(stdin, message: Dict) -> None:
    stdin.write(json.dumps(message) + "\n")
    stdin.flush()


_CODEX_EOF = object()


def _codex_reader(stdout, messages: queue.Queue) -> None:
    try:
        while True:
            line = stdout.readline()
            if line == "":
                break
            messages.put(line)
    except Exception as exc:  # pragma: no cover - defensive for real process I/O failures
        messages.put(exc)
    finally:
        messages.put(_CODEX_EOF)


def _codex_next_message(messages: queue.Queue, deadline: float) -> Dict:
    remaining = deadline - time.monotonic()
    if remaining <= 0:
        raise TimeoutError("Timed out waiting for Codex app-server response")

    try:
        item = messages.get(timeout=remaining)
    except queue.Empty as exc:
        raise TimeoutError("Timed out waiting for Codex app-server response") from exc

    if item is _CODEX_EOF:
        raise RuntimeError("Codex app-server process closed stdout before sending a response")

    if isinstance(item, Exception):
        raise RuntimeError(f"Codex app-server stream error: {item}")

    line = str(item).strip()
    if not line:
        return _codex_next_message(messages, deadline)

    try:
        return json.loads(line)
    except json.JSONDecodeError as exc:
        preview = line[:200]
        raise RuntimeError(f"Malformed Codex app-server JSON: {preview}") from exc


def _codex_error_text(message: Dict) -> str:
    error = message.get("error")
    if isinstance(error, dict):
        return str(error.get("message") or error)
    if error:
        return str(error)
    params = message.get("params") or {}
    if isinstance(params, dict):
        return str(params.get("error") or params.get("message") or message)
    return str(message)


def _codex_extract_thread_id(result: Dict) -> Optional[str]:
    thread_id = result.get("threadId") or result.get("thread_id")
    if thread_id:
        return str(thread_id)
    thread = result.get("thread")
    if isinstance(thread, dict) and thread.get("id"):
        return str(thread["id"])
    return None


def _codex_extract_delta(message: Dict) -> str:
    method = str(message.get("method", ""))
    if "agentMessage" not in method and "agent_message" not in method and "delta" not in method:
        return ""

    params = message.get("params") or {}
    if not isinstance(params, dict):
        return ""

    candidates = [params.get("delta"), params.get("text")]
    for key in ("item", "message"):
        nested = params.get(key)
        if isinstance(nested, dict):
            candidates.extend([nested.get("delta"), nested.get("text")])

    for value in candidates:
        if isinstance(value, str):
            return value
    return ""


def _codex_terminal(message: Dict) -> Optional[bool]:
    method = str(message.get("method", "")).lower()
    params = message.get("params") or {}
    status_value = params.get("status") if isinstance(params, dict) else None
    status_text = str(status_value or "").lower()

    if "turn/error" in method or status_text in {"failed", "cancelled", "canceled", "error"}:
        return False
    if (
        "turn/complete" in method
        or "turn/completed" in method
        or "turn/finished" in method
        or status_text in {"completed", "succeeded", "success"}
    ):
        return True
    return None


def _codex_wait_for_response(messages: queue.Queue, request_id: int, deadline: float) -> Dict:
    while True:
        message = _codex_next_message(messages, deadline)
        if message.get("id") == request_id:
            if message.get("error"):
                raise RuntimeError(_codex_error_text(message))
            result = message.get("result")
            return result if isinstance(result, dict) else {}

        terminal = _codex_terminal(message)
        if terminal is False:
            raise RuntimeError(_codex_error_text(message))


def _codex_collect_turn(messages: queue.Queue, turn_request_id: int, deadline: float) -> str:
    chunks = []
    while True:
        message = _codex_next_message(messages, deadline)
        if message.get("id") == turn_request_id and message.get("error"):
            raise RuntimeError(_codex_error_text(message))

        delta = _codex_extract_delta(message)
        if delta:
            chunks.append(delta)

        terminal = _codex_terminal(message)
        if terminal is True:
            return "".join(chunks)
        if terminal is False:
            raise RuntimeError(_codex_error_text(message))


def _call_codex_app_server_stdio(prompt: str, system: str, max_tokens: int, temperature: float, json_output: bool, model: Optional[str] = None) -> Dict:
    """Call official Codex app-server over stdio JSON-RPC-like messages."""
    del max_tokens, temperature  # Codex app-server thread/start does not use these fields here.

    model = model or _env("CODEX_APP_SERVER_MODEL", "gpt-5.5")
    timeout = float(_env("CODEX_APP_SERVER_TIMEOUT", "300"))
    command = _env("CODEX_APP_SERVER_COMMAND", "codex")
    cwd = _env("CODEX_APP_SERVER_CWD") or os.getcwd()
    sandbox = _env("CODEX_APP_SERVER_SANDBOX", "read-only")
    approval_policy = _env("CODEX_APP_SERVER_APPROVAL_POLICY", "never")

    process = None
    try:
        process = subprocess.Popen(
            [command, "app-server", "--listen", "stdio://"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
            bufsize=1,
        )
    except FileNotFoundError as exc:
        raise RuntimeError(
            f"Codex app-server command not found: {command}. Set CODEX_APP_SERVER_COMMAND or install Codex CLI with app-server support."
        ) from exc

    try:
        if process.stdin is None or process.stdout is None:
            raise RuntimeError("Codex app-server stdio pipes were not available")

        messages: queue.Queue = queue.Queue()
        reader = threading.Thread(target=_codex_reader, args=(process.stdout, messages), daemon=True)
        reader.start()
        deadline = time.monotonic() + timeout

        initialize_id = 1
        thread_id_request = 2
        turn_id = 3

        _codex_send(
            process.stdin,
            {
                "jsonrpc": "2.0",
                "id": initialize_id,
                "method": "initialize",
                "params": {"clientInfo": {"name": "Warp", "version": "0.1.0"}},
            },
        )
        _codex_wait_for_response(messages, initialize_id, deadline)

        _codex_send(process.stdin, {"jsonrpc": "2.0", "method": "initialized", "params": {}})
        _codex_send(
            process.stdin,
            {
                "jsonrpc": "2.0",
                "id": thread_id_request,
                "method": "thread/start",
                "params": {
                    "cwd": cwd,
                    "ephemeral": True,
                    "model": model,
                    "approvalPolicy": approval_policy,
                    "sandbox": sandbox,
                },
            },
        )
        thread_result = _codex_wait_for_response(messages, thread_id_request, deadline)
        thread_id = _codex_extract_thread_id(thread_result)
        if not thread_id:
            raise RuntimeError("Codex app-server thread/start did not return a threadId")

        _codex_send(
            process.stdin,
            {
                "jsonrpc": "2.0",
                "id": turn_id,
                "method": "turn/start",
                "params": {
                    "threadId": thread_id,
                    "input": [{"type": "text", "text": _codex_app_server_input_text(prompt, system, json_output)}],
                },
            },
        )
        text = _codex_collect_turn(messages, turn_id, deadline)

        return {
            "ok": True,
            "text": text,
            "provider": "codex_app_server",
            "model": model,
            "error": None,
        }
    finally:
        if process.stdin:
            try:
                process.stdin.close()
            except Exception:
                pass
        if process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=2)
            except subprocess.TimeoutExpired:
                process.kill()


def _call_codex_app_server(prompt: str, system: str, max_tokens: int, temperature: float, json_output: bool, model: Optional[str] = None) -> Dict:
    """Call official Codex app-server using its direct app-server transport."""
    try:
        transport = _env("CODEX_APP_SERVER_URL", "stdio://") or "stdio://"
        if transport == "stdio://":
            return _call_codex_app_server_stdio(prompt, system, max_tokens, temperature, json_output, model)
        raise ValueError(f"Unsupported Codex app-server transport: {transport}. Warp currently supports stdio://.")
    except Exception as e:
        return {"ok": False, "error": str(e), "provider": "codex_app_server"}


def status() -> Dict:
    """Get status of all configured providers."""
    providers_status = {}

    for provider_id, config in PROVIDERS.items():
        env_var = config.get("env_var")
        if provider_id == "codex_app_server":
            transport = _env(env_var, "stdio://") or "stdio://"
            configured = transport == "stdio://" or transport.startswith(("ws://", "wss://", "unix://"))
            providers_status[provider_id] = {
                "name": config["name"],
                "configured": configured,
                "transport": transport,
                "supported": transport == "stdio://",
            }
        elif env_var and env_var != "None":
            has_key = bool(_env(env_var))
            providers_status[provider_id] = {
                "name": config["name"],
                "configured": has_key,
            }
        else:
            providers_status[provider_id] = {
                "name": config["name"],
                "configured": True,
            }

    return {
        "providers": providers_status,
        "default_order": DEFAULT_PROVIDER_ORDER,
    }


if __name__ == "__main__":
    result = call_with_fallback("Hello, how are you?")
    print(json.dumps(result, indent=2))
