     1|#!/usr/bin/env python3
     2|"""
     3|Warp — LLM Gateway
     4|Multi-provider LLM client with automatic fallback.
     5|Auto-generated by Agent Factory.
     6|"""
     7|import os
     8|import json
     9|import logging
    10|from typing import Optional, Dict, List
    11|
    12|logging.basicConfig(level=logging.INFO)
    13|log = logging.getLogger("llm_gateway")
    14|
    15|PROVIDERS = {
    16|    "anthropic": {
    17|        "name": "Anthropic Claude",
    18|        "env_var": "ANTHROPIC_API_KEY",
    19|    },
    20|    "openai": {
    21|        "name": "OpenAI",
    22|        "env_var": "OPENAI_API_KEY",
    23|    },
    24|    "openrouter": {
    25|        "name": "OpenRouter",
    26|        "env_var": "OPENROUTER_API_KEY",
    27|    },
    28|}
    29|
    30|
    31|def _env(key: str, default=None):
    32|    """Get environment variable."""
    33|    return os.environ.get(key, default)
    34|
    35|
    36|def call_with_fallback(
    37|    prompt: str,
    38|    providers: List[str] = None,
    39|    system: str = None,
    40|    max_tokens: int = 4096,
    41|    temperature: float = 0.7,
    42|    json_output: bool = False,
    43|) -> Dict:
    44|    """
    45|    Call LLM with automatic fallback across providers.
    46|
    47|    Returns:
    48|        {
    49|            "ok": True/False,
    50|            "text": "response text",
    51|            "provider": "provider_name",
    52|            "model": "model_name",
    53|            "error": None or error message
    54|        }
    55|    """
    56|    providers = providers or ['anthropic', 'openai', 'openrouter']
    57|
    58|    for provider in providers:
    59|        try:
    60|            result = _call_provider(provider, prompt, system, max_tokens, temperature, json_output)
    61|            if result.get("ok"):
    62|                return result
    63|        except Exception as e:
    64|            log.warning(f"{provider} failed: {e}")
    65|            continue
    66|
    67|    return {"ok": False, "error": "All providers failed", "text": ""}
    68|
    69|
    70|def _call_provider(
    71|    provider: str,
    72|    prompt: str,
    73|    system: str,
    74|    max_tokens: int,
    75|    temperature: float,
    76|    json_output: bool,
    77|) -> Dict:
    78|    """Call a specific provider."""
    79|
    80|    if provider not in PROVIDERS:
    81|        raise ValueError(f"Unknown provider: {provider}")
    82|
    83|    config = PROVIDERS[provider]
    84|
    85|    
    86|    if provider == "anthropic":
    87|        return _call_anthropic(prompt, system, max_tokens, temperature, json_output)
    88|    
    89|
    90|    
    91|    if provider == "openai":
    92|        return _call_openai(prompt, system, max_tokens, temperature, json_output)
    93|    
    94|
    95|    
    96|
    97|    
    98|
    99|    raise NotImplementedError(f"Provider {provider} not implemented")
   100|
   101|
   102|
   103|def _call_anthropic(prompt: str, system: str, max_tokens: int, temperature: float, json_output: bool) -> Dict:
   104|    """Call Anthropic Claude API."""
   105|    try:
   106|        import anthropic
   107|        api_key = _env("ANTHROPIC_API_KEY")
   108|        if not api_key:
   109|            raise ValueError("ANTHROPIC_API_KEY not set")
   110|
   111|        client = anthropic.Anthropic(api_key=api_key)
   112|
   113|        messages = [{"role": "user", "content": prompt}]
   114|
   115|        response = client.messages.create(
   116|            model="claude-sonnet-4-7",
   117|            max_tokens=max_tokens,
   118|            temperature=temperature,
   119|            system=system or "You are a helpful AI assistant.",
   120|            messages=messages,
   121|        )
   122|
   123|        text = response.content[0].text
   124|
   125|        return {
   126|            "ok": True,
   127|            "text": text,
   128|            "provider": "anthropic",
   129|            "model": response.model,
   130|            "error": None,
   131|        }
   132|    except Exception as e:
   133|        return {"ok": False, "error": str(e), "provider": "anthropic"}
   134|
   135|
   136|
   137|
   138|def _call_openai(prompt: str, system: str, max_tokens: int, temperature: float, json_output: bool) -> Dict:
   139|    """Call OpenAI API."""
   140|    try:
   141|        import openai
   142|        api_key = _env("OPENAI_API_KEY")
   143|        if not api_key:
   144|            raise ValueError("OPENAI_API_KEY not set")
   145|
   146|        client = openai.OpenAI(api_key=api_key)
   147|
   148|        messages = [
   149|            {"role": "system", "content": system or "You are a helpful AI assistant."},
   150|            {"role": "user", "content": prompt}
   151|        ]
   152|
   153|        response = client.chat.completions.create(
   154|            model="gpt-4o",
   155|            messages=messages,
   156|            max_tokens=max_tokens,
   157|            temperature=temperature,
   158|        )
   159|
   160|        text = response.choices[0].message.content
   161|
   162|        return {
   163|            "ok": True,
   164|            "text": text,
   165|            "provider": "openai",
   166|            "model": response.model,
   167|            "error": None,
   168|        }
   169|    except Exception as e:
   170|        return {"ok": False, "error": str(e), "provider": "openai"}
   171|
   172|
   173|
   174|
   175|
   176|
   177|def status() -> Dict:
   178|    """Get status of all configured providers."""
   179|    providers_status = {}
   180|
   181|    for provider_id, config in PROVIDERS.items():
   182|        env_var = config.get("env_var")
   183|        if env_var and env_var != "None":
   184|            has_key = bool(_env(env_var))
   185|            providers_status[provider_id] = {
   186|                "name": config["name"],
   187|                "configured": has_key,
   188|            }
   189|        else:
   190|            # Local provider
   191|            providers_status[provider_id] = {
   192|                "name": config["name"],
   193|                "configured": True,
   194|            }
   195|
   196|    return {
   197|        "providers": providers_status,
   198|        "default_order": ['anthropic', 'openai', 'openrouter'],
   199|    }
   200|
   201|
   202|if __name__ == "__main__":
   203|    # Test
   204|    result = call_with_fallback("Hello, how are you?")
   205|    print(json.dumps(result, indent=2))