#!/usr/bin/env python3
"""
Axsupport — Orchestrator
NL query router: analyze_context + run_tools + synthesize.
Auto-generated by Agent Factory.
"""
import json
import os
import sys
import subprocess
import time
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
sys.path.insert(0, str(SCRIPT_DIR))

from config import get
from llm_gateway import call_with_fallback, status as llm_status

TOOLS_DIR = SCRIPT_DIR / "tools"
SYSTEM_PROMPT_PATH = SCRIPT_DIR.parent / "prompts" / "system-prompt.md"


def load_system_prompt() -> str:
    """Load system prompt with fallback."""
    try:
        with open(SYSTEM_PROMPT_PATH) as f:
            return f.read().strip()
    except:
        return (
            "You are Axsupport, an AI assistant. "
            "Autonomous customer support operations agent for triage, classification, routing, drafting, knowledge lookup, SLA management, and helpdesk automation. "
            "Be concise, specific, and actionable."
        )


# Tool Registry
TOOLS = {

    "slack": {
        "script": "slack_tool.py",
        "args": [],
        "purpose": "Slack integration",
    },

    "notion": {
        "script": "notion_tool.py",
        "args": [],
        "purpose": "Notion integration",
    },

}


def analyze_context(goal: str) -> list:
    """
    Analyze query and return which tools should run.
    Keyword-based routing.
    """
    goal_lower = goal.lower()
    needed = []






    if any(kw in goal_lower for kw in ["slack", "message", "channel"]):
        needed.append("slack")




    return needed if needed else list(TOOLS.keys())[:1] if TOOLS else []


def run_tool(tool_name: str, args: list = None, quiet: bool = False) -> dict:
    """Execute a tool and return its output."""
    if tool_name not in TOOLS:
        return {"error": f"Unknown tool: {tool_name}", "tool": tool_name}

    tool = TOOLS[tool_name]
    script_path = TOOLS_DIR / tool["script"]
    args = args or tool.get("args", [])

    if not quiet:
        print(f"  🔍 Running {tool_name}...")

    start_time = time.time()

    try:
        cmd = ["python3", str(script_path)] + args
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        elapsed = time.time() - start_time

        if result.returncode == 0:
            if not quiet:
                print(f"     ✓ Completed in {elapsed:.2f}s")
            try:
                data = json.loads(result.stdout)
                data["_execution_time"] = round(elapsed, 2)
                return data
            except:
                return {"raw": result.stdout, "tool": tool_name, "_execution_time": round(elapsed, 2)}
        else:
            if not quiet:
                print(f"     ✗ Failed after {elapsed:.2f}s")
            return {"error": result.stderr, "tool": tool_name, "_execution_time": round(elapsed, 2)}
    except Exception as e:
        elapsed = time.time() - start_time
        return {"error": str(e), "tool": tool_name, "_execution_time": round(elapsed, 2)}


def llm_synthesize(goal: str, tool_results: list, provider: str = None, quiet: bool = False) -> str:
    """Use LLM to synthesize response from tool results."""
    results_text = _format_tool_results(tool_results)
    system = load_system_prompt()

    prompt = f"""Goal: {goal}

Tool Results:
{results_text}

Synthesize a clear, actionable response."""

    providers = get("llm.providers", ['anthropic', 'openai', 'openrouter'])
    if provider:
        providers = [p for p in providers if p == provider] + providers

    if not quiet:
        print(f"\n🤖 Synthesizing response...")

    result = call_with_fallback(
        prompt,
        providers=providers,
        system=system,
        max_tokens=get("llm.max_tokens", 4096),
        temperature=get("llm.temperature", 0.7),
    )

    if result.get("ok"):
        if not quiet:
            model_used = result.get("model", "unknown")
            prov = result.get("provider", "unknown")
            print(f"   ✓ Using {prov}/{model_used}")
        return result["text"]

    return _synthesize_logic(goal, tool_results)


def _format_tool_results(results: list) -> str:
    """Format tool results for prompt."""
    parts = []
    for r in results:
        if not isinstance(r, dict):
            parts.append(str(r))
            continue
        tool = r.get("tool", "unknown")
        if "error" in r:
            parts.append(f"[{tool}] ERROR: {r['error']}")
            continue
        parts.append(f"[{tool}]")
        for k, v in r.items():
            if k == "tool":
                continue
            if isinstance(v, (list, dict)):
                parts.append(f"  {k}: {json.dumps(v, ensure_ascii=False)[:500]}")
            else:
                parts.append(f"  {k}: {str(v)[:500]}")
    return "\n".join(parts) if parts else "(no results)"


def _synthesize_logic(goal: str, tool_results: list) -> str:
    """Fallback logic-based synthesis."""
    parts = []
    for result in tool_results:
        if isinstance(result, dict):
            if "error" in result:
                parts.append(f"Error: {result['error']}")
            elif "message" in result:
                parts.append(result["message"])
            elif "data" in result:
                parts.append(json.dumps(result["data"], indent=2)[:500])
            else:
                parts.append(json.dumps(result, indent=2)[:500])
    return "\n".join(parts) if parts else "No results."


def orchestrate(goal: str, use_llm: bool = True, provider: str = None, quiet: bool = False) -> str:
    """
    Main entry point: analyze goal, run tools, synthesize response.
    """
    if not quiet:
        print(f"🎯 Axsupport: {goal}")

    # Analyze and select tools
    needed_tools = analyze_context(goal)
    if not quiet:
        print(f"🛠️  Tools: {needed_tools}")

    # Execute tools
    results = []
    for tool in needed_tools:
        result = run_tool(tool, quiet=quiet)
        if result:
            results.append(result)

    # Synthesize
    if use_llm:
        response = llm_synthesize(goal, results, provider=provider, quiet=quiet)
    else:
        response = _synthesize_logic(goal, results)

    return response


if __name__ == "__main__":
    use_llm = True
    provider = None
    goal_parts = []

    for i, arg in enumerate(sys.argv[1:]):
        if arg == "--no-llm":
            use_llm = False
        elif arg == "--provider" and i + 1 < len(sys.argv[1:]):
            provider = sys.argv[1:][i + 2]
        elif arg in ("--status", "-s"):
            st = llm_status()
            print(json.dumps(st, indent=2))
            sys.exit(0)
        else:
            goal_parts.append(arg)

    goal = " ".join(goal_parts) if goal_parts else "help"
    response = orchestrate(goal, use_llm=use_llm, provider=provider)
    print("\n" + "=" * 50)
    print(response)
    print("=" * 50)